// src/styles/modalStyles.js
export const styles = {
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    animationDuration: '0.25s',
    animationFillMode: 'forwards',
  },
  fadeIn: {
    animationName: 'fadeIn',
    opacity: 1,
  },
  fadeOut: {
    animationName: 'fadeOut',
    opacity: 0,
  },
  '@keyframes fadeIn': {
    from: { opacity: 0 },
    to: { opacity: 1 },
  },
  '@keyframes fadeOut': {
    from: { opacity: 1 },
    to: { opacity: 0 },
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '2rem',
    width: '500px',
    maxWidth: '90%',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
  },
  header: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#5ca67c',
    marginBottom: '1rem',
  },
  input: {
    width: '100%',
    padding: '0.75rem',
    borderRadius: '8px',
    border: '1px solid #ccc',
    marginBottom: '1rem',
    fontSize: '1rem',
  },
  inputError: {
    borderColor: '#f44336',
  },
  secondaryButton: {
    padding: '0.5rem 1rem',
    borderRadius: '8px',
    border: '1px solid #5ca67c',
    backgroundColor: '#fff',
    color: '#5ca67c',
    fontWeight: 500,
    cursor: 'pointer',
    marginBottom: '1rem',
  },
  removeButton: {
    padding: '0.5rem 1rem',
    borderRadius: '8px',
    border: '1px solid #E39292',
    backgroundColor: '#fff',
    color: '#E39292',
    fontWeight: 500,
    cursor: 'pointer',
    marginBottom: '1rem',
  },
  primaryButton: {
    padding: '0.75rem 1.5rem',
    borderRadius: '8px',
    backgroundColor: '#5ca67c',
    color: '#fff',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    marginRight: '1rem',
  },
  cancelButton: {
    padding: '0.75rem 1.5rem',
    borderRadius: '8px',
    backgroundColor: '#f44336',
    color: '#fff',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
  },
  buttonRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '1.5rem',
  },
  errorText: {
    color: '#f44336',
    fontSize: '0.85rem',
    marginTop: '-10px',
    marginBottom: '10px',
  },
  headerRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
}
