// src/styles/editGroupModalStyles.js
export const styles = {
  modalBackdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100vw',
    height: '100vh',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    padding: '2rem',
    width: '500px',
    maxWidth: '90%',
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
  },
  inputGroup: {
    marginBottom: '1rem',
    display: 'flex',
    flexDirection: 'column',
  },
  label: {
    marginBottom: '0.5rem',
    fontWeight: '600',
    color: '#023D54',
    fontSize: '1rem',
  },
  input: {
    width: '100%',
    padding: '0.75rem',
    borderRadius: '8px',
    border: '1px solid #ccc',
    fontSize: '1rem',
  },
  buttonRow: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: '1.5rem',
    gap: '1rem',
  },
  submitButton: {
    padding: '0.75rem 1.5rem',
    borderRadius: '8px',
    backgroundColor: '#5ca67c',
    color: '#fff',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
  },
  cancelButton: {
    padding: '0.75rem 1.5rem',
    borderRadius: '8px',
    backgroundColor: '#f44336',
    color: '#fff',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
  },
  select: {
    width: '100%',
    padding: '8px 12px',
    fontSize: '16px',
    borderRadius: '12px',
    border: '1px solid #BFE4C2',
    outline: 'none',
    cursor: 'pointer',
    transition: 'border-color 0.3s ease',
    marginBottom: '12px',
  },
  modalHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '1rem',
  },
  newLabButton: {
    padding: '0.5rem 1rem',
    borderRadius: '8px',
    backgroundColor: '#0277bd', // deep blue to contrast green & red
    color: '#fff',
    fontWeight: 'bold',
    border: 'none',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
  },
  newLabButtonHover: {
    backgroundColor: '#015a8a',
  },
}
