const styles = {
  card: {
    width: '320px',
    minHeight: '180px',
    backgroundColor: '#fff',
    borderRadius: '20px',
    border: '1px solid #BFE4C2',
    boxShadow: '0 8px 20px rgba(0, 0, 0, 0.12)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    cursor: 'pointer',
    padding: '20px',
    transition:
      'transform 0.25s ease, box-shadow 0.25s ease, border 0.25s ease',
    fontFamily: "'SF Pro Text', 'Helvetica Neue', Helvetica, Arial, sans-serif",
  },
  cardHover: {
    transform: 'scale(1.05)',
    boxShadow: '0 12px 32px rgba(0, 0, 0, 0.18)',
    border: '1.5px solid #277233',
  },
  cardTitle: {
    fontSize: '22px',
    fontWeight: 600,
    color: '#277233',
    textAlign: 'center',
    marginBottom: '16px',
  },
  select: {
    width: '100%',
    padding: '8px 12px',
    fontSize: '16px',
    borderRadius: '12px',
    border: '1px solid #BFE4C2',
    outline: 'none',
    cursor: 'pointer',
    transition: 'border-color 0.3s ease',
    marginBottom: '12px',
  },
  variableRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '6px 0',
    borderBottom: '1px solid #eee',
  },
  variableName: {
    fontWeight: 500,
    fontSize: '14px',
    color: '#333',
    flex: 1,
    paddingRight: '8px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  variableValue: {
    fontSize: '15px',
    color: '#555',
    flex: 2,
    textAlign: 'right',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
}

export default styles
