export const styles = {
  container: {
    padding: '30px',
    backgroundColor: '#F5F5F5',
    minHeight: '100vh',
    fontFamily: 'Inter, sans-serif',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '12px',
    marginBottom: '20px',
  },
  experimentName: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#023D54',
    textAlign: 'center',
  },
  editButton: {
    backgroundColor: 'transparent',
    border: 'none',
    cursor: 'pointer',
    color: '#5ca67c',
    fontSize: '20px',
    padding: '4px',
  },
  schoolsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: '12px',
    marginBottom: '30px',
  },
  schoolChip: {
    backgroundColor: '#E0F2F1',
    color: '#023D54',
    padding: '6px 12px',
    borderRadius: '20px',
    fontSize: '14px',
    fontWeight: '500',
  },
  sectionContainer: {
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    padding: '20px',
    marginBottom: '20px',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.05)',
    borderLeft: '4px solid #5ca67c',
    width: '100%',
    maxWidth: '800px',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    marginBottom: '10px',
    color: '#5ca67c',
  },
  textarea: {
    width: '100%',
    minHeight: '120px',
    borderRadius: '8px',
    border: '1px solid #ccc',
    padding: '10px',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'vertical',
    marginBottom: '10px',
  },
  submitButton: {
    backgroundColor: '#388E3C',
    color: '#fff',
    padding: '8px 16px',
    borderRadius: '8px',
    border: 'none',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
    marginBottom: '8px',
  },
  statusText: {
    fontSize: '12px',
    fontStyle: 'italic',
    color: '#757575',
  },
  schoolLink: {
    fontWeight: '500',
    color: '#023D54',
    transition: 'color 0.2s ease, text-decoration 0.2s ease',
    cursor: 'pointer',
  },

  schoolLinkHover: {
    color: '#5ca67c',
    textDecoration: 'underline',
  },
}
